# Generated by Django 3.2.13 on 2022-06-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quality', models.CharField(max_length=50)),
                ('material_id', models.CharField(max_length=50)),
                ('worth', models.FloatField()),
                ('file_source', models.TextField()),
            ],
        ),
    ]
