# Generated by Django 3.2.13 on 2022-06-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampledata',
            old_name='material_id',
            new_name='material',
        ),
    ]
