# Generated by Django 3.2.13 on 2022-06-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0002_rename_material_id_sampledata_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampledata',
            old_name='material',
            new_name='material_name',
        ),
    ]
